### ISSUE TITLE
Audd.io API Error: Cannot fetch lyrics

### ISSUE THREAD

**Issue by plibither8** [mkossoris/YouTube-Music-Mini#1]
Hi! Great extension, really useful. Since around the past week I have not been able to fetch lyrics for the song that I am listening to. I just inspected the console and got the following error logged:

```
{status: "error", error: {…}, requested_params: {…}, see api documentation: "https://docs.audd.io", contact us: "api@audd.io"}contact us: "api@audd.io"error: {error_code: 900, error_message: "Lyrics searching failed: authorization failed: wrong api_token."}requested_params: {method: "findLyrics", q: "kanye west  runaway"}see api documentation: "https://docs.audd.io"status: "error"__proto__: Object

Lyrics.js:37 Uncaught TypeError: Cannot read property '0' of undefined
    at XMLHttpRequest.xhr.onreadystatechange (Lyrics.js:37)
```

Screenshot: 
![image](https://user-images.githubusercontent.com/31861755/66271169-9250d000-e878-11e9-89a2-4c6ef3817106.png)

Seems like your API token is incorrect or has expired - it would be great if you could look into this. Thanks!

**Comment by mkossoris** [comment]
Never closed this but this issue has been resolved :).
